on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps: 
    - run: "echo Job ${{ github.com }}"

  job_2:
   runs-on: ubuntu-latest
   needs: job_1
   steps:
   - run: "echo Job ${{ github.com }}"

   
  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps: 
    - run: "echo Job ${{ github.com }}"   

  job_4:
    runs-on: ubuntu-latest
    needs: [job_2,job_3]
    steps: 
    - run: "echo Job ${{ github.com }}"     
