on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install and build
        run: |
          npm install
          npm run build
        working-directory: ./temp
        shell: bash

      - name: Print environment variables with Perl
        run: |
          perl -e 'print "$_ => $ENV{$_}\n" for keys %ENV;'
        shell: bash
